Repository t98s/minecraft-server, pull requests merged in 2022-05, with the labels that each got.

#18 Stop using for_each with output values
  actions.tf
Labels: plan-all-ready

#21 OS Login には VM に割り当てられている SA へ成る権限が必要らしい
  operator.tf
Labels: add-or-update

#22 Change terraform dir
  .github/workflows/terraform.yml
  terraform/.terraform.lock.hcl
  terraform/actions.tf
  terraform/main.tf
  terraform/operator.tf
  terraform/services.tf
  terraform/services_for_sa.tf
  terraform/starter.tf
  terraform/starter_iam.tf
  terraform/variables.tf
Labels: destroy
